const { MyObject,CreateObject,add } = require('../build/Release/myobject.node')

const o1 = new MyObject(23)
const o2 = new MyObject(67)
console.log(o1.plusOne())
console.log(o2.plusOne())
console.log(MyObject)
console.log(add(o1,o2))
const o3 = CreateObject(11)
const o4 = CreateObject(77)
console.log(o3.plusOne())
console.log(o4.plusOne())
console.log(CreateObject)
console.log(add(o3,o4))